### ISSUE TITLE
media-utils install failing in Node-RED Raspberry Pi

### ISSUE THREAD

**Issue by kent1026** [ibm-early-programs/node-red-contrib-media-utils#11] opened 2018-01-09 05:38 UTC
use palette and npm install media-utils 
print:
root@raspberrypi:~/.node-red# npm install node-red-contrib-media-utils
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> easy-ffmpeg@0.0.14 postinstall /root/.node-red/node_modules/easy-ffmpeg
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/.node-red/node_modules/easy-ffmpeg/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
node-red-project@0.0.1 /root/.node-red
└── (empty)

npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-media-utils"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! easy-ffmpeg@0.0.14 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-ffmpeg@0.0.14 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the easy-ffmpeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs easy-ffmpeg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls easy-ffmpeg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
npm ERR! code 1

npm -v :3.10.10
node -v:v6.12.3

**Comment by chughts** [comment] 2018-01-09 14:58
This is a duplicate of #10 . uuid is a dependancy of a dependancy If this is easy-ffmpeg, then we are already at the latest version 0.0.14. 

This needs investigation as to where node-uuid is being required.

**Closed as completed** 2018-01-09 15:07 UTC
